### ISSUE TITLE
Could you please provide some documents or explanation of codes?

### ISSUE THREAD

**Issue by WilliamWangPeng** [VadimGush/raytracing#1]
Hi dear author,  
    It's a great honor to open one issue here, truly honor.  I just begin to learn computer graphics and have compiled your program successfully, but it is hard for me to read the codes, could you please provide some explanation or PPT or papers about the code to me?   👍 

thank you  
Best Regards with kindness  
William

**Comment by VadimGush** [comment]
@WilliamWangPeng Hi. I will sent you just a list of materials that I used:

 1. https://www.amazon.com/Ray-Tracing-Weekend-Minibooks-Book-ebook/dp/B01B5AODD8 - very simple and great introduction to raytracing.
  2. https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html - CUDA programming guide for GPGPU.
  3. https://youtu.be/lGmPy8xpT4E - great lecture on GPU architecture and programming models.

Seems like that's all. I open for any other questions if you will have one.

**Comment by VadimGush** [comment]
@WilliamWangPeng And information about denoiser that I still didn't include in my project you can find here: https://www.openimagedenoise.org/

**Comment by WilliamWangPeng** [comment]
> @WilliamWangPeng Hi. I will sent you just a list of materials that I used:
> 
> 1. https://www.amazon.com/Ray-Tracing-Weekend-Minibooks-Book-ebook/dp/B01B5AODD8 - very simple and great introduction to raytracing.
> 2. https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html - CUDA programming guide for GPGPU.
> 3. https://youtu.be/lGmPy8xpT4E - great lecture on GPU architecture and programming models.
> 
> Seems like that's all. I open for any other questions if you will have one.

thank you dear @VadimGush   
    It's very nice of you,   🥇   :-)
    I will try to read the codes following the main document you have given me,  It's such a gift in the Teachers' Day 👍   

thank you  
best regards  
William
